apiVersion: v1
kind: Secret
metadata:
  name: llm-secrets
  namespace: llm
type: Opaque
stringData:
  API_KEY: ""
  HF_TOKEN: ""

  # Add these
  POSTGRES_USER: "llm"
  POSTGRES_PASSWORD: "llm"
  POSTGRES_DB: "llm"

  # And for the app pods (api + job)
  DATABASE_URL: "postgresql+asyncpg://llm:llm@postgres:5432/llm"
  REDIS_URL: "redis://redis:6379/0"