global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Prometheus scraping itself (through /prometheus route prefix)
  - job_name: "prometheus"
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ["prometheus:9090"]

  # LLM server API
  - job_name: "llm_server_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]