# infra/prometheus.yml
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "llm_api_container"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus:9090"]
