kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: llm
nodes:
  - role: control-plane
    extraPortMappings:
      # Optional: if/when you add ingress later, 80/443 are nice to have
      - containerPort: 80
        hostPort: 8081
        protocol: TCP
      - containerPort: 443
        hostPort: 8444
        protocol: TCP